"""change embedding to vector

Revision ID: 2acfc6c66fb2
Revises: 40fef407eb31
Create Date: 2026-02-10 13:45:17.281872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2acfc6c66fb2'
down_revision = '40fef407eb31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
