"""create orders table

Revision ID: 3f315f815b04
Revises: d3b0aef6099a
Create Date: 2026-02-04 15:55:36.269536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f315f815b04'
down_revision = 'd3b0aef6099a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
