"""add created_at to orders

Revision ID: 40fef407eb31
Revises: 3f315f815b04
Create Date: 2026-02-04 17:29:16.495462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fef407eb31'
down_revision = '3f315f815b04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_orders_id', table_name='orders')
    op.create_index(op.f('ix_public_orders_id'), 'orders', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_orders_id'), table_name='orders', schema='public')
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
