"""Add embedding column or change dimension

Revision ID: ff7d5bf8477f
Revises: 2acfc6c66fb2
Create Date: 2026-02-10 15:48:03.963485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7d5bf8477f'
down_revision = '2acfc6c66fb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
